# ########## EPEX Spot Integration ##########
#
# homeassistant:
#   min_version: 2024.10.1
# domain: template sensor
#
# source_url: https://github.com/heinemannj/huawei_solar_hems/blob/main/config/packages/epexspot.yaml
#
# repository_name: Huawei Solar HEMS
# repository_description: Home Assistent (HA) Home Energy Management System (HEMS)
# repository_url: https://github.com/heinemannj/huawei_solar_hems
# documentation_url: https://github.com/heinemannj/huawei_solar_hems/wiki
# author: https://github.com/heinemannj
#
# Copyright (c) 2024 Joerg Heinemann
# All rights reserved.
#
# license: https://github.com/heinemannj/huawei_solar_hems/blob/main/LICENSE
#
# ########## Entities ##########
#
# - automation.epex_spot_fetch_data
#
# - binary_sensor.epex_spot_data_update
#
# - sensor.epex_spot_data_price
# - sensor.epex_spot_data_net_price
# - sensor.epex_spot_data_quantile
#
# ########## Start: Persistent Template Sensors ##########
#
template:
  - trigger:
      - platform: time_pattern
        minutes: "/1"
    action:
      - variables:
          data_update: "{{ states('binary_sensor.epex_spot_data_update') }}"
          last_update: "{{ state_attr('binary_sensor.epex_spot_data_update', 'last_update') }}"
          next_poll_time: "{{ state_attr('binary_sensor.epex_spot_data_update', 'next_poll_time') }}"
          data: "{{ state_attr('sensor.epex_spot_data_net_price', 'data') }}"
          APIUpdate: >-
            {% from 'epexspot.jinja' import APIUpdate %}
            {{ APIUpdate(data_update, last_update, next_poll_time, data)|from_json }}
    binary_sensor:
      - name: "epex_spot_data_update"
        unique_id: epex_spot_data_update
        icon: mdi:clock
        state: >-
          {{ APIUpdate.tomorrow_data_available }}
        attributes:
          last_data: "{{ APIUpdate.last_data }}"
          last_api_update: "{{ APIUpdate.last_update }}"
          next_poll_time: "{{ APIUpdate.next_poll_time }}"
          last_updated: "{{ now().isoformat() }}"
#
# ########## End: Persistent Template Sensors ##########
