# ########## Heat Pump - SG-Ready controller ##########
#
# homeassistant:
#   min_version: 2024.10.1
# domain: template sensor
#
# source_url: https://github.com/heinemannj/huawei_solar_hems/blob/main/config/packages/heat-pump-sg-ready-control.yaml
#
# repository_name: Huawei Solar HEMS
# repository_description: Home Assistent (HA) Home Energy Management System (HEMS)
# repository_url: https://github.com/heinemannj/huawei_solar_hems
# documentation_url: https://github.com/heinemannj/huawei_solar_hems/wiki
# author: https://github.com/heinemannj
#
# license: https://github.com/heinemannj/huawei_solar_hems/blob/main/LICENSE
# Copyright (c) 2024 Joerg Heinemann
#
# ########## Entities ##########
#
# - sensor.sg_ready_mode
#
# ########## Start: Persistent Template Sensors ##########
#
template:
  - trigger:
      - platform: time_pattern
        minutes: "/1"
    action:
      - variables:
          t: "{{ now().isoformat() }}"
          var: >-
            {% from '032-emhass.jinja' import globalVariables %}
            {{ globalVariables()|from_json }}
          epexspot_quantile: "{{ states(var.epexspot_quantile)|float(0) }}"
          grid_active_power: "{{ states(var.grid_active_power)|float(0) }}"
          hp_lock: "{{ states(var.sg_ready_hp_lock) }}"
          pv_excess: "{{ states(var.sg_ready_pv_excess) }}"
    sensor:
      #
      # SG-Ready mode
      #
      # - for SG-Ready controller/automation
      #
      - name: "SG-Ready Operating mode control"
        unique_id: sg-ready-mode
        state: >-
          {% if hp_lock == 'off' and pv_excess == 'off' %}
            {{ 'Normal' }}
          {% elif hp_lock == 'on' and pv_excess == 'off' %}
            {{ 'Lock' }}
          {% elif hp_lock == 'off' and pv_excess == 'on' %}
            {{ 'Recommendation' }}
          {% elif hp_lock == 'on' and pv_excess == 'on' %}
            {{ 'Turn On' }}
          {% else %}
            {{ 'Unavailable' }}
          {% endif %}
        attributes:
          mode: >-
            {% if epexspot_quantile|float(0) >= var.epexspot_quantile_setpoint_high|float(0)
                and grid_active_power <= 1000 %}
              {{ 'Lock' }}
            {% elif epexspot_quantile|float(0) <= var.epexspot_quantile_setpoint_neutral|float(0)
                and grid_active_power >= 1800 %}
              {{ 'Turn On' }}
            {% elif epexspot_quantile|float(0) <= var.epexspot_quantile_setpoint_low|float(0) %}
              {{ 'Recommendation' }}
            {% else %}
              {{ 'Normal' }}
            {% endif %}
          hp_lock: "{{ hp_lock }}"
          pv_excess: "{{ pv_excess }}"
          last_updated: "{{ t }}"
#
# ########## End: Template Sensors ##########
