# Loads default set of integrations. Do not remove.
default_config:

homeassistant:
  packages:
    huawei_solar_power: !include packages/huawei_solar_power.yaml
    garden_solar_power: !include packages/garden_solar_power.yaml

automation: !include automations.yaml
lovelace: !include ui-lovelace.yaml
script: !include scripts.yaml

frontend:
  themes: !include_dir_merge_named themes

# Text to speech
tts:
  - platform: google_translate

# https zugriff
http:
  use_x_forwarded_for: true
  trusted_proxies:
    - 192.168.1.0/24

recorder:
  purge_keep_days: 14
  commit_interval: 20