# ########## Heating Pump - SG-Ready controller ##########
#
# homeassistant:
#   min_version: 2024.10.1
# domain: automation
#
# source_url: https://github.com/heinemannj/huawei_solar_hems/blob/main/config/blueprints/automation/hems/heating-pump-sg-ready-control.yaml
#
# repository_name: Huawei Solar HEMS
# repository_description: Home Assistent (HA) Home Energy Management System (HEMS)
# repository_url: https://github.com/heinemannj/huawei_solar_hems
# documentation_url: https://github.com/heinemannj/huawei_solar_hems/wiki
# author: https://github.com/heinemannj
#
# license: https://github.com/heinemannj/huawei_solar_hems/blob/main/LICENSE
# Copyright (c) 2024 Joerg Heinemann
#
# ########## Entities ##########
#
# - automation.heating_pump_sg_ready_control
#
# ########## Start: Blueprint ##########
#
blueprint:
  name: heating_pump_sg_ready_control
  description: >-
    ## Heating Pump - SG-Ready controller

    * automation.heating_pump_sg_ready_control

    ### Home Assistent (HA) Home Energy Management System (HEMS)

    * Min HA version: 2024.10.1

    * Domain: automation

    * Source: https://github.com/heinemannj/huawei_solar_hems/blob/main/config/blueprints/automation/hems/heating-pump-sg-ready-control.yaml

    #### Repository

    * [Huawei Solar HEMS](https://github.com/heinemannj/huawei_solar_hems)

    * [Documentation](https://github.com/heinemannj/huawei_solar_hems/wiki)

    #### Author
    
    * [heinemannj](https://github.com/heinemannj)

    #### License

    * [Copyright (c) 2024 Joerg Heinemann](https://github.com/heinemannj/huawei_solar_hems/blob/main/LICENSE)

  domain: automation
  homeassistant:
    min_version: 2024.10.1
  author: heinemannj
  source_url: https://github.com/heinemannj/huawei_solar_hems/blob/main/config/blueprints/automation/hems/heating-pump-sg-ready-control.yaml
  input:
    sg_ready_mode:
      name: SG-Ready mode
      description: Actual mode of SG-Ready controller.
      selector:
        entity:
          filter:
            - domain: sensor
          include_entities:
            - sensor.sg_ready_mode
          multiple: false
    sg_ready_evu:
      name: SG-Ready EVU switch
      description: EVU switch of SG-Ready controller.
      selector:
        entity:
          domain: switch
          multiple: false
    sg_ready_pv_ma:
      name: SG-Ready PV_ma switch
      description: PV_ma switch of SG-Ready controller.
      selector:
        entity:
          domain: switch
          multiple: false
    domestic_hot_water_0_boost:
      name: domestic_hot_water_0_boost
      description: domestic_hot_water_0_boost.
      selector:
        entity:
          domain: switch
          multiple: false
#
# ########## Start: Automation ##########
#
id: 'heating_pump_sg_ready_control'
alias: 'Heating Pump - SG-Ready controller'
description: 'Heating Pump: SG-Ready controller.'
triggers:
- trigger: time_pattern
  minutes: /1
conditions: []
actions:
- choose:
  - conditions:
    - condition: state
      entity_id: !input sg_ready_mode
      attribute: mode
      state: EVU lock
    sequence:
    - if:
      - condition: state
        entity_id: !input sg_ready_evu
        state: 'off'
      then:
      - metadata: {}
        data: {}
        target:
          entity_id: !input sg_ready_evu
        action: switch.turn_on
    - if:
      - condition: state
        entity_id: !input sg_ready_pv_ma
        state: 'on'
      then:
      - metadata: {}
        data: {}
        target:
          entity_id: !input sg_ready_pv_ma
        action: switch.turn_off
    - if:
      - condition: state
        entity_id: !input domestic_hot_water_0_boost
        state: 'on'
      then:
      - metadata: {}
        data: {}
        target:
          entity_id: !input domestic_hot_water_0_boost
        action: switch.turn_off
  default:
  - if:
    - condition: state
      entity_id: !input sg_ready_evu
      state: 'on'
    then:
    - metadata: {}
      data: {}
      target:
        entity_id: !input sg_ready_evu
      action: switch.turn_off
  - if:
    - condition: state
      entity_id: !input sg_ready_pv_ma
      state: 'on'
    then:
    - metadata: {}
      data: {}
      target:
        entity_id: !input sg_ready_pv_ma
      action: switch.turn_off
  - if:
    - condition: state
      entity_id: !input domestic_hot_water_0_boost
      state: 'on'
    then:
    - metadata: {}
      data: {}
      target:
        entity_id: !input domestic_hot_water_0_boost
      action: switch.turn_off
mode: single
#
# ########## End: Automation ##########
