# ########## Huawei Solar - Batteries Charge-Discharge control ##########
#
# homeassistant:
#   min_version: 2024.10.1
# domain: automation
#
# source_url: https://github.com/heinemannj/huawei_solar_hems/blob/main/config/blueprints/automation/hems/huawei-solar-batteries-charge-discharge-control.yaml
#
# repository_name: Huawei Solar HEMS
# repository_description: Home Assistent (HA) Home Energy Management System (HEMS)
# repository_url: https://github.com/heinemannj/huawei_solar_hems
# documentation_url: https://github.com/heinemannj/huawei_solar_hems/wiki
# author: https://github.com/heinemannj
#
# Copyright (c) 2024 Joerg Heinemann
# All rights reserved.
#
# license: https://github.com/heinemannj/huawei_solar_hems/blob/main/LICENSE
#
# ########## Entities ##########
#
# - automation.huawei_solar_batteries_charge_discharge_control
#
# ########## Start: Blueprint ##########
#
blueprint:
  name: Huawei Solar - Batteries Charge-Discharge Control
  description: >-
    <br>
    **Batteries Charge-Discharge Management** for Huawei LUNA2000-5/10/15-S0 connected to Huawei SUN2000-3/4/5/6/8/10KTL-M1 Inverter.

    * automation.huawei_solar_batteries_charge_discharge_control

    ### Home Assistent (HA) Home Energy Management System (HEMS)

    * Min HA version: 2024.10.1

    * Domain: automation

    * [Source](https://github.com/heinemannj/huawei_solar_hems/blob/main/config/blueprints/automation/hems/huawei-solar-batteries-charge-discharge-control.yaml)

    #### Repository

    * [Huawei Solar HEMS](https://github.com/heinemannj/huawei_solar_hems)

    * [Documentation](https://github.com/heinemannj/huawei_solar_hems/wiki)

    #### Author
    
    * [heinemannj](https://github.com/heinemannj)

    #### License

    * [Copyright (c) 2024 Joerg Heinemann](https://github.com/heinemannj/huawei_solar_hems/blob/main/LICENSE)

    * All rights reserved.

  domain: automation
  homeassistant:
    min_version: 2024.10.1
  author: heinemannj
  source_url: https://github.com/heinemannj/huawei_solar_hems/blob/main/config/blueprints/automation/hems/huawei-solar-batteries-charge-discharge-control.yaml
  input:
    batteries_charge_discharge_control_settings:
      name: Batteries Charge-Discharge controller settings
      icon: mdi:cog
      description: Configure sensors, binary sensors, switches, input numbers and devices for Batteries Charge-Discharge control.
      input:
        binary_sensor_batteries_forcible_charge:
          name: HEMS Batteries Forcible charge control binary sensor
          description: >-
            Forcible charge binary sensor of HEMS batteries controller.
            <br>
            <br>Default: binary_sensor.batteries_forcible_charge
          selector:
            entity:
              domain: binary_sensor
              multiple: false
          default: binary_sensor.batteries_forcible_charge
        binary_sensor_batteries_charge_from_grid:
          name: HEMS Batteries Charge from grid control binary sensor
          description: >-
            Charge from grid binary sensor of HEMS batteries controller.
            <br>
            <br>Default:  binary_sensor.batteries_charge_from_grid
          selector:
            entity:
              domain: binary_sensor
              multiple: false
          default: binary_sensor.batteries_charge_from_grid
        binary_sensor_batteries_maximum_charging_power:
          name: HEMS Batteries Maximum charging power control binary sensor
          description: >-
            Maximum charge power binary sensor of HEMS batteries controller.
            <br>
            <br>Default: binary_sensor.batteries_maximum_charging_power
          selector:
            entity:
              domain: binary_sensor
              multiple: false
          default: binary_sensor.batteries_maximum_charging_power
        binary_sensor_batteries_maximum_discharging_power:
          name: HEMS Batteries Maximum discharging power control binary sensor
          description: >-
            Maximum discharge power binary sensor of HEMS batteries controller.
            <br>
            <br>Default: binary_sensor.batteries_maximum_discharging_power
          selector:
            entity:
              domain: binary_sensor
              multiple: false
          default: binary_sensor.batteries_maximum_discharging_power
        sensor_batteries_maximum_charge_power:
          name: Huawei Solar Batteries Rated charge power sensor
          description: >-
            Rated charge power sensor of PV system's Batteries device.
            <br>
            <br>Default: sensor.batteries_maximum_charge_power
          selector:
            entity:
              multiple: false
              filter:
                - domain: sensor
                  device_class: power
          default: sensor.batteries_maximum_charge_power
        sensor_batteries_maximum_discharge_power:
          name: Huawei Solar Batteries Rated discharge power sensor
          description: >-
            Rated discharge power sensor of PV system's Batteries device.
            <br>
            <br>Default: sensor.batteries_maximum_discharge_power
          selector:
            entity:
              multiple: false
              filter:
                - domain: sensor
                  device_class: power
          default: sensor.batteries_maximum_discharge_power
        sensor_batteries_forcible_charge:
          name: Huawei Solar Batteries Forcible charge sensor
          description: >-
            Forcible charge sensor of PV system's Batteries device.
            <br>
            <br>Default: sensor.batteries_forcible_charge
          selector:
            entity:
              domain: sensor
              multiple: false
          default: sensor.batteries_forcible_charge
        switch_batteries_charge_from_grid:
          name: Huawei Solar Batteries Charge from grid switch
          description: >-
            Charge from grid switch of PV system's Batteries device.
            <br>
            <br>Default: switch.batteries_charge_from_grid
          selector:
            entity:
              domain: switch
              multiple: false
          default: switch.batteries_charge_from_grid
        number_batteries_maximum_charging_power:
          name: Huawei Solar Batteries Maximum charge power number
          description: >-
            Maximum charge power number of PV system's Batteries device.
            <br>
            <br>Default: number.batteries_maximum_charging_power
          selector:
            entity:
              domain: number
              multiple: false
          default: number.batteries_maximum_charging_power
        batteries_device:
          name: Huawei Solar Batteries device
          description: PV system's Batteries device.
          selector:
            device:
              integration: huawei_solar
              multiple: false
        trigger_frequency:
          name: Trigger frequency
          description: >-
            Set the `time_pattern` for the automation trigger (in minutes).
            <br>
            <br>Default: /1; Will match every 1 minutes.
            <br>Note: Must start with a `/`
          default: "/1"
          selector:
            text:
#
# ########## Start: Automation ##########
#
id: 'huawei_solar_batteries_charge_discharge_control'
alias: 'Huawei Solar - Batteries Charge-Discharge Control'
description: 'Batteries Charge-Discharge Management for Huawei LUNA2000-5/10/15-S0 connected to Huawei SUN2000-3/4/5/6/8/10KTL-M1 Inverter'
trigger:
- platform: time_pattern
  minutes: !input trigger_frequency
variables:
  bat_rated_charge_power_id: !input sensor_batteries_maximum_charge_power
  bat_rated_charge_power: "{{ states(bat_rated_charge_power_id)|float(5000) }}"
  bat_rated_discharge_power_id: !input sensor_batteries_maximum_discharge_power
  bat_rated_discharge_power: "{{ states(bat_rated_discharge_power_id)|float(5000) }}"
  bat_forcible_charge_id: !input binary_sensor_batteries_forcible_charge
  bat_target_soc: "{{ state_attr(bat_forcible_charge_id, 'bat_target_soc')|float(100) }}"
  bat_target_charge_power_id: !input binary_sensor_batteries_maximum_charging_power
  bat_target_charge_power: "{{ state_attr(bat_target_charge_power_id, 'maximum_charging_power') }}"
  bat_max_charge_power_id: !input number_batteries_maximum_charging_power
  bat_max_charge_power: "{{ states(bat_max_charge_power_id)|int }}"
condition: []
action:
- choose:
  - conditions:
    - condition: state
      entity_id: !input binary_sensor_batteries_charge_from_grid
      state: 'on'
    sequence:
    - if:
      - condition: state
        entity_id: !input sensor_batteries_forcible_charge
        state: Stop
        attribute: mode
      then:
      - data:
          target_soc: '{{ bat_target_soc|float(100) }}'
          power: '{{ bat_rated_charge_power|float(5000) }}'
          device_id: !input batteries_device
        action: huawei_solar.forcible_charge_soc
    - if:
      - condition: state
        entity_id: !input switch_batteries_charge_from_grid
        state: 'off'
      then:
      - metadata: {}
        data: {}
        target:
          entity_id: !input switch_batteries_charge_from_grid
        action: switch.turn_on
    alias: 'EMHASS and EPEX spot price controlled Batteries Charging from Grid - Forcible Charge = ON - Charge from Grid = ON'
  - conditions:
    - condition: state
      entity_id: !input binary_sensor_batteries_forcible_charge
      state: 'on'
    sequence:
    - if:
      - condition: state
        entity_id: !input sensor_batteries_forcible_charge
        state: Stop
        attribute: mode
      then:
      - data:
          target_soc: '{{ bat_target_soc|float(100) }}'
          power: '{{ bat_rated_charge_power|float(5000) }}'
          device_id: !input batteries_device
        action: huawei_solar.forcible_charge_soc
    - if:
      - condition: state
        entity_id: !input switch_batteries_charge_from_grid
        state: 'on'
      then:
      - metadata: {}
        data: {}
        target:
          entity_id: !input switch_batteries_charge_from_grid
        action: switch.turn_off
    alias: 'EPEX spot price controlled Batteries Charging - Forcible Charge = ON - Charge from Grid = OFF'
  - conditions:
    - condition: state
      entity_id: !input binary_sensor_batteries_maximum_charging_power
      state: 'off'
    sequence:
    - if:
      - condition: template
        value_template: >-
          {%- set actual = bat_max_charge_power|int %}
          {%- set target = bat_target_charge_power|int %}
          {{ iif(target > 0 and not 98 < actual/target*100 < 102) }}
      then:
      - data:
          value: '{{ bat_target_charge_power|int }}'
        target:
          entity_id: !input number_batteries_maximum_charging_power
        action: number.set_value
    - if:
      - condition: state
        entity_id: !input sensor_batteries_forcible_charge
        state: Charge
        attribute: mode
      then:
      - data:
          device_id: !input batteries_device
        action: huawei_solar.stop_forcible_charge
    - if:
      - condition: state
        entity_id: !input switch_batteries_charge_from_grid
        state: 'on'
      then:
      - metadata: {}
        data: {}
        target:
          entity_id: !input switch_batteries_charge_from_grid
        action: switch.turn_off
    alias: 'Solar Forecast controlled Batteries Charging Power - Forcible Charge = OFF - Charge from Grid = OFF'
  - conditions:
    - condition: and
      conditions:
      - condition: state
        entity_id: !input binary_sensor_batteries_maximum_discharging_power
        state: 'off'
    sequence:
    - if:
      - condition: state
        entity_id: !input sensor_batteries_forcible_charge
        state: Stop
        attribute: mode
      then:
      - data:
          target_soc: '{{ bat_target_soc|float(100) }}'
          power: '{{ bat_rated_charge_power|float(5000) }}'
          device_id: !input batteries_device
        action: huawei_solar.forcible_charge_soc
    - if:
      - condition: state
        entity_id: !input switch_batteries_charge_from_grid
        state: 'on'
      then:
      - metadata: {}
        data: {}
        target:
          entity_id: !input switch_batteries_charge_from_grid
        action: switch.turn_off
    alias: 'EPEX spot price controlled Batteries Discharging - Discharge = OFF - Charge from Grid = OFF'
  default:
  - if:
    - condition: template
      value_template: >-
        {%- set actual = bat_max_charge_power|int %}
        {%- set target = bat_target_charge_power|int %}
        {{ iif(actual != target) }}
    then:
    - data:
        value: '{{ bat_target_charge_power|int }}'
      target:
        entity_id: !input number_batteries_maximum_charging_power
      action: number.set_value
  - if:
    - condition: state
      entity_id: !input sensor_batteries_forcible_charge
      state: Charge
      attribute: mode
    then:
    - data:
        device_id: !input batteries_device
      action: huawei_solar.stop_forcible_charge
  - if:
    - condition: state
      entity_id: !input switch_batteries_charge_from_grid
      state: 'on'
    then:
    - metadata: {}
      data: {}
      target:
        entity_id: !input switch_batteries_charge_from_grid
      action: switch.turn_off
    alias: 'Normal mode - Forcible Charge = OFF - Charge from Grid = OFF'
mode: single
#
# ########## End: Automation ##########
